"""CDP Input domain wrapper.

Provides :class:`InputDomain` — typed methods for the CDP ``Input``
domain that dispatch mouse and keyboard events to the browser.

Key methods:
    - :meth:`dispatch_mouse_event` — simulate mouse interactions
    - :meth:`dispatch_key_event` — simulate keyboard interactions
    - :meth:`insert_text` — insert text as if from an IME
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING, Any

from pathlight_mcp.cdp.domains._base import CDPDomain

if TYPE_CHECKING:
    from pathlight_mcp.cdp.session import CDPSession

__all__ = ["InputDomain"]

logger = logging.getLogger(__name__)


class InputDomain(CDPDomain):
    """Typed wrapper for the CDP ``Input`` domain.

    Dispatches mouse and keyboard events to the browser.

    Args:
        session: The active CDP session to send commands through.
    """

    domain = "Input"

    def __init__(self, session: CDPSession) -> None:
        super().__init__(session)

    def dispatch_mouse_event(
        self,
        type: str,
        x: float,
        y: float,
        *,
        button: str = "none",
        click_count: int = 0,
        modifiers: int = 0,
        delta_x: float = 0.0,
        delta_y: float = 0.0,
    ) -> None:
        """Dispatch a mouse event.

        Sends ``Input.dispatchMouseEvent``.

        Args:
            type: Event type (``"mousePressed"``, ``"mouseReleased"``,
                ``"mouseMoved"``, ``"mouseWheel"``).
            x: X coordinate relative to the viewport.
            y: Y coordinate relative to the viewport.
            button: Mouse button (``"none"``, ``"left"``, ``"middle"``,
                ``"right"``, ``"back"``, ``"forward"``).
            click_count: Number of times the button was clicked.
            modifiers: Bitmask of modifier keys.
            delta_x: X delta for ``mouseWheel`` events.
            delta_y: Y delta for ``mouseWheel`` events.
        """
        params: dict[str, Any] = {
            "type": type,
            "x": x,
            "y": y,
            "button": button,
            "clickCount": click_count,
            "modifiers": modifiers,
        }
        if type == "mouseWheel":
            params["deltaX"] = delta_x
            params["deltaY"] = delta_y

        self._send(self._method("dispatchMouseEvent"), params)

    def dispatch_key_event(
        self,
        type: str,
        *,
        key: str = "",
        code: str = "",
        key_identifier: str = "",
        windows_virtual_key_code: int = 0,
        native_virtual_key_code: int = 0,
        modifiers: int = 0,
        text: str = "",
        unmodified_text: str = "",
        auto_repeat: bool = False,
        is_keypad: bool = False,
        is_system_key: bool = False,
        location: int = 0,
        commands: list[str] | None = None,
    ) -> None:
        """Dispatch a key event.

        Sends ``Input.dispatchKeyEvent``.

        Args:
            type: Event type (``"keyDown"``, ``"keyUp"``, ``"rawKeyDown"``,
                ``"char"``).
            key: Key value (e.g. ``"a"``, ``"Enter"``, ``"Tab"``).
            code: Physical key code (e.g. ``"KeyA"``, ``"Enter"``).
            key_identifier: Legacy key identifier.
            windows_virtual_key_code: Windows virtual key code.
            native_virtual_key_code: Native virtual key code.
            modifiers: Bitmask of modifier keys.
            text: Text generated by the key (for ``"char"`` events).
            unmodified_text: Text without modifiers applied.
            auto_repeat: Whether this is an auto-repeated key press.
            is_keypad: Whether the key is on the keypad.
            is_system_key: Whether this is a system key event.
            location: Key location (0=standard, 1=left, 2=right, 3=numpad).
            commands: List of DOM editing commands for ``"keyDown"``.
        """
        params: dict[str, Any] = {
            "type": type,
            "modifiers": modifiers,
        }
        if key:
            params["key"] = key
        if code:
            params["code"] = code
        if text:
            params["text"] = text
        if key_identifier:
            params["keyIdentifier"] = key_identifier
        if windows_virtual_key_code:
            params["windowsVirtualKeyCode"] = windows_virtual_key_code
        if native_virtual_key_code:
            params["nativeVirtualKeyCode"] = native_virtual_key_code
        if unmodified_text:
            params["unmodifiedText"] = unmodified_text
        if auto_repeat:
            params["autoRepeat"] = True
        if is_keypad:
            params["isKeypad"] = True
        if is_system_key:
            params["isSystemKey"] = True
        if location:
            params["location"] = location
        if commands:
            params["commands"] = commands

        self._send(self._method("dispatchKeyEvent"), params)

    def insert_text(self, text: str) -> None:
        """Insert text as if from an IME.

        Sends ``Input.insertText``.

        Args:
            text: The text to insert.
        """
        self._send(self._method("insertText"), {"text": text})

    def emulate_touch_from_mouse_event(
        self,
        type: str,
        x: float,
        y: float,
        *,
        button: str = "left",
        timestamp: float | None = None,
        delta_x: float = 0.0,
        delta_y: float = 0.0,
        modifiers: int = 0,
        touch_start: bool = False,
    ) -> None:
        """Emulate a touch event from a mouse event.

        Sends ``Input.emulateTouchFromMouseEvent``.

        Args:
            type: Event type (``"mousePressed"``, ``"mouseReleased"``,
                ``"mouseMoved"``, ``"mouseWheel"``).
            x: X coordinate.
            y: Y coordinate.
            button: Mouse button.
            timestamp: Event timestamp.
            delta_x: X delta for wheel events.
            delta_y: Y delta for wheel events.
            modifiers: Modifier key bitmask.
            touch_start: Whether this is a touch start event.
        """
        params: dict[str, Any] = {
            "type": type,
            "x": int(x),
            "y": int(y),
            "button": button,
            "modifiers": modifiers,
        }
        if timestamp is not None:
            params["timestamp"] = timestamp
        if type == "mouseWheel":
            params["deltaX"] = int(delta_x)
            params["deltaY"] = int(delta_y)

        self._send(self._method("emulateTouchFromMouseEvent"), params)

    def set_ignore_input_events(self, ignore: bool) -> None:
        """Ignore or un-ignore input events.

        Sends ``Input.setIgnoreInputEvents``.

        Args:
            ignore: Whether to ignore input events.
        """
        self._send(self._method("setIgnoreInputEvents"), {"ignore": ignore})
